# Generated by Django 2.2.5 on 2019-09-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
